route:
    receiver: 'slack'
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Prometheus'
            channel: '#random'
            api_url: 'https://hooks.slack.com/services/xxx/xxx/xxx'
      webhook_configs:
          - send_resolved: true
            url: 'http://alertmanager-bot:7070'
    