apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    name: pv1
spec:
  storageClassName: pvskinuploads
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/anle/User/github/note/k8s/uploads"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  labels:
    name: pv2
spec:
  storageClassName: pvmongodb
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/anle/User/github/note/k8s/mongo"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
  namespace: nginx-ingress
  labels:
    name: pv3
spec:
  storageClassName: pvskinupload
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/anle/User/github/note/k8s/uploads"