apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    name: pvc1
spec:
  storageClassName: pvskinuploads
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
  labels:
    name: pvc2
spec:
  storageClassName: pvmongodb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2000Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    name: pvc1
  namespace: nginx-ingress
spec:
  storageClassName: pvskinupload
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Mi